### PR TITLE
Performance Audit 

### PR DESCRIPTION
**Pull request by AnsarIbrahim**
# This PR Contains:

- Make sure that you have your database set up with the schema and data from your previous projects.✅
- Run the following query to add an extra column to the owners table✅
- Run the following statements to add data to your database✅
- Depending on your machine speed✅

## Project requirements:

**1. SELECT COUNT(*) FROM visits where animal_id = 4;**

- Before:

- After:

**2. SELECT * FROM visits where vet_id = 2;**
- Before:

- After:

**3. SELECT * FROM owners where email = 'owner_18327@mail.com';**
- Before:

- After:

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Data, queries and schema added ✔️
- Explained Analyse made for slow DB queries ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
@AnsarIbrahim I mistakenly required changes, I will submit a form to fix it, apology please.

**Comment by AnsarIbrahim** [comment]
No issues ☺️

**Comment by enniopo** [comment]
@AnsarIbrahim @supreeti, the activity´s status has been manually changed to completed on your dashboard. 
Please refresh the page to see it.

**Comment by Olamarx** [comment]
> @AnsarIbrahim @supreeti, the activity´s status has been manually changed to completed on your dashboard. Please refresh the page to see it.

Thank you, @enniopo

**Pull request merged**
